### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by BharatSingh1008** [PixelExperience/official_devices#2302]
## Device you want to apply for
```
twolip - Xiaomi Note 6pro
```

## Device tree sources

```
https://github.com/BharatSingh1008/android_device_xiaomi_twolip
https://github.com/PixelExperience-Devices/device_xiaomi_sdm660-common
https://github.com/LineageOS/android_kernel_xiaomi_sdm660
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_sdm660-common
https://github.com/BharatSingh1008/vendor_xiaomi_twolip
```

## Number of ROM's you maintain officially
```
0
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@BharatSingh1008
```

### GitHub username
```
https://github.com/BharatSingh1008
```

**Comment by UltraLegend61** [comment]
Waiting for Redmi Note 6pro to be Official

**Comment by Hasaber8** [comment]
Few observations:-
1. You don't need to set a build fp, PE does that.
2. If you are using PE-sdm660-common Xiaomi, then you should also use the same kernel. Because as far as I remember PE sdm660-common Xiaomi uses Pixel Power Hal.
3. Also you have just cherry-picked the whole tree and your git account is very new so we can't determine if you have any experience working on the device.
CC: @Hlcpereira

**Comment by Hlcpereira** [comment]
The only other possibility if you want to use Lineage's kernel is fully decommonize the device, and then use those decommonized trees as a reference.

Yet: Some changes on your tree that were made shows a lack of experience from you which would be enough to mark this application as rejected, but also they are not that big of a deal.

**Comment by BharatSingh1008** [comment]
bro I have decommonized the device trees & removed Stock fp and now building , I want to know a thing that if Build done succesfully and Stable Then is There any Other issue as you said before lack of experience..... 

OR i have to apply again in future with more work @Hlcpereira

**Comment by Hlcpereira** [comment]
The main reason why I said that was to do with some overlays that doesn't exist on the ROM code.

For example: config_forceShowNetworkTrafficOnStatusBar

And also now this commit: https://github.com/BharatSingh1008/android_device_xiaomi_twolip/commit/46b6343d7d6bd87e70bf89f8adba8d89ad2581a2

The commit message passes the idea of being a full decommonization (that being unifying the common-tree with the device specific tree), while it's nowhere near it. And seems more like that you just squashed import the LOS device-specific tree for twolip over it, while the proper way to do would be a rebase. Just as per this one commit that I linked, it can be considered, again, enough to reject this application, as it kills the original authorship from Lineage.

With that said, thanks for applying, but unfortunately, due to your lack of experience and the issues with authorship that you brought up now with the lastest commit, this application is considered as rejected. Feel free to reapply in the future
