### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ItsMeVedansh** [PixelExperience/official_devices#2321]
## Device you want to apply for

Redmi Y2/S2 (YSL)

## Device tree sources

https://github.com/ItsMeVedansh/device_xiaomi_ysl
https://github.com/ItsMeVedansh/logan_ysl
https://github.com/ItsMeVedansh/android_vendor_xiaomi_ysl

## Number of ROM's you maintain officially

2

## Any Exceptions/special concern?

No

### Telegram username

https://t.me/ItsMeZyrus

### GitHub username

https://github.com/ItsMeVedansh

**Comment by jjpprrrr** [comment]
Hi there. Thanks for the application. There are a bunch of kernel changes that are against the CoC of PE. Please read the CoC carefully and revise them accordingly. 

Here are a couple examples:

- Boeffla wakelock blocker
  - https://github.com/ItsMeVedansh/logan_ysl/commit/37fffea5d1b100aa859a29b71b6b260af70cacdb
- Any form of overclocking/underclocking
  - https://github.com/ItsMeVedansh/logan_ysl/commit/9c3cf01e7f05bbd68e5d68446b3657a629670a92

**Comment by Hlcpereira** [comment]
As a complement: On tree side it was noticed a lot of random picking and ricing, with some of them end up being an issue due to compliance with our CoC.

Together with the kernel side patches, including those that @jjpprrrr mentioned, it does make this application as rejected.

Thanks for applying anyway, and feel free to reapply in the future
Best regards
