### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by muhammad23012009** [PixelExperience/official_devices#2322]
## Device you want to apply for

Motorola Moto E5+

## Device tree sources

https://github.com/muhammad23012009/android_device_motorola_hannah
https://github.com/muhammad23012009/android_device_motorola_hannah-common
https://github.com/muhammad23012009/android_device_motorola_msm8937-common
https://github.com/muhammad23012009/android_kernel_motorola_msm8953
https://github.com/Themuppets/proprietary_vendor_motorola

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

MotoActions needs to be added

### Telegram username

t.me/TheVancedGamer

### GitHub username

github.com/muhammad23012009

**Comment by Jorg3Lucas** [comment]
Hi, we appreciate your interest in being part of our project. Unfortunately we can't accept you because you don't have contributions in device sources, you just renamed it from the LineageOS organization and in addition, the device will not support Android 12 with the expected quality due to the hardware limitations that the device has.
