### ISSUE TITLE
Request maintaining Mi 10T device for PE12

### ISSUE THREAD

**Issue by Fenix46** [PixelExperience/official_devices#2487]
## Device you want to apply for

Xiaomi Mi 10T

## Device tree sources

https://github.com/Fenix46/device_xiaomi_apollo
https://github.com/Fenix46/kernel_xiaomi_apollo
https://github.com/Fenix46/vendor_xiaomi

## Number of ROM's you maintain officially

0

## Any Exceptions/special concern?

No

### Telegram username

Fenix46

### GitHub username

Fenix46

**Comment by Hlcpereira** [comment]
We still have a maintainer for apollo. Therefor this application is rejected on the basis that it isn't available for a new maintainship

**Comment by Fenix46** [comment]
Ok... But I see all the work of the maintainer, and at this Moment he don't have Plan an update to A12 from what I see, and I use a standalone device tree that I think Is Better. not considering a job, just because the maintainer is present, when he hasn't even planned an update to date, is a joke.  anyway, you decide so I won't say any more, I've already wasted enough breath

**Comment by Hlcpereira** [comment]
That's where you're the most wrong about.

We indeed have in force an item in our code of conduct that the maintainers, not mattering when it's a normal member or an admin/core member, must release monthly, however we have in mind that everyone has a life outside of the Android custom ROM development, plus the fact that we don't even receive a salary to pay our bills while spending all of our free time in it.

Twelve support for apollo was confirmed exactly two weeks ago, same as the other devices he also work on, those being sweet, begonia, sakura, mojito and alioth, due to the fact that maintainer have been away due to important tests in his country since October.

Just because no work has been seen on the device sources public repos, it doesn't mean that the maintainer haven't being working one the device tree in private repos :ok_hand:.

**Comment by Hasaber8** [comment]
@Fenix46 sorry to have wasted your breath. Please don't apply again though, just an precaution to save your breath
:-)

**Comment by Fenix46** [comment]
ok message received. sorry if i looked arrogant.

**Comment by usmanovms** [comment]
Isn't co-maintaining available? Considering Zidan's multiple devices and several drops in last 6 months having a person working with him would be great. He himself does co-maintain half of his devices, no? Hope you got me right and thanks for your freee and yet stunning work guys.
