### ISSUE TITLE
New maintainer for Xiaomi Redmi Note 4/4X

### ISSUE THREAD

**Issue by NRanjan-17** [PixelExperience/official_devices#2664]
## Device you want to apply for

Xiaomi Redmi Note 4/4X

## Device tree sources

https://github.com/NRanjan-17/device_xiaomi_mido_pixel
https://github.com/NRanjan-17/proprietary_vendor_xiaomi
https://github.com/NRanjan-17/android_kernel_xiaomi_mido

## Number of ROM's you maintain officially

Zero

## Any Exceptions/special concern?

No

### Telegram username

@HyperPower17

### GitHub username

NRanjan-17

**Comment by ArixElo** [comment]
Hi, let's start by saying that I am not one of the assigned members, but an accepted maintainer. And my goal in this comment is to make you aware of what you are doing wrong. And I've seen that you're keep trying despite the fact that you were rejected for 3 times.
Let me tell you why:
![Screenshot_20220426-145932_Vivaldi Browser](https://user-images.githubusercontent.com
![Screenshot_20220426-145943_Vivaldi Browser](https://user-images.githubusercontent.com/36364890/165306996-566e1a2c-4afd-4388-97dc-c207af9bccd6.png)
![Screenshot_20220426-145950_Vivaldi Browser](https://user-images.githubusercontent.com/36364890/165307000-20a2b5ad-8979-4177-a685-051cea7f7ea7.png)
![Screenshot_20220426-145953_Vivaldi Browser](https://user-images.githubusercontent.com/36364890/165307004-e6e77a24-757d-4b6f-b3e6-06d7f4b25321.png)
/36364890/165306984-86da8391-605e-471f-8ad3-0355ef1d933f.png)
![Screenshot_20220426-145937_Vivaldi Browser](https://user-images.githubusercontent.com/36364890/165306993-acbde89e-e2d1-4bde-b64d-b605afef573c.png)
This isn't how commits should like, and even you killed authorship for some of them.
And because of that you've broke the second point of Pixel Experience Maintainers requirements:
**_2 - You must have a good knowledge of git._**
So my advice is: close your application, try to learn git even more (I'm not saying that I'm the expert in it, but I do know things that are required) and then apply again if you feel that you're learned it a lot.
For me it was 4 years of making ROMs for countless amount of people.
Bye!

**Comment by KakatkarAkshay** [comment]
> Hi, let's start by saying that I am not one of the assigned members, but an accepted maintainer. And my goal in this comment is to make you aware of what you are doing wrong. And I've seen that you're keep trying despite the fact that you were rejected for 3 times. Let me tell you why: ![Screenshot_20220426-145932_Vivaldi Browser](https://user-images.githubusercontent.com ![Screenshot_20220426-145943_Vivaldi Browser](https://user-images.githubusercontent.com/36364890/165306996-566e1a2c-4afd-4388-97dc-c207af9bccd6.png) ![Screenshot_20220426-145950_Vivaldi Browser](https://user-images.githubusercontent.com/36364890/165307000-20a2b5ad-8979-4177-a685-051cea7f7ea7.png) ![Screenshot_20220426-145953_Vivaldi Browser](https://user-images.githubusercontent.com/36364890/165307004-e6e77a24-757d-4b6f-b3e6-06d7f4b25321.png) /36364890/165306984-86da8391-605e-471f-8ad3-0355ef1d933f.png) ![Screenshot_20220426-145937_Vivaldi Browser](https://user-images.githubusercontent.com/36364890/165306993-acbde89e-e2d1-4bde-b64d-b605afef573c.png) This isn't how commits should like, and even you killed authorship for some of them. And because of that you've broke the second point of Pixel Experience Maintainers requirements: **_2 - You must have a good knowledge of git._** So my advice is: close your application, try to learn git even more (I'm not saying that I'm the expert in it, but I do know things that are required) and then apply again if you feel that you're learned it a lot. For me it was 4 years of making ROMs for countless amount of people. Bye!

Pretty much sums it up. Also you should stop reapplying again and again if you are rejected. Unless you want to get banned from organization I guess.

**Comment by NRanjan-17** [comment]
I know but these are my old commits and reverting the commit again to fix errors , is this wrong. and my latest commit had been fixed .
https://github.com/NRanjan-17/frameworks_opt_telephony/commit/b04b3388b6ed67869759d4f03b436f47054b9b2c
https://github.com/NRanjan-17/frameworks_opt_telephony/commit/d2ed97c1475f04bd15d1610bd7503502756660cd
https://github.com/NRanjan-17/frameworks_opt_telephony/commit/15f08e33df4bd64fb26bc5dbec0389598ccdb51f

https://github.com/NRanjan-17/system_bt-1/commit/967d5ba4402ed46298b87cb67540e5d8957381a2
https://github.com/NRanjan-17/system_bt-1/commit/66347b202321df1aaa20704b5dc79e6b31e99072

**Comment by KakatkarAkshay** [comment]
Revert is different that authorship

**Comment by NRanjan-17** [comment]
i also mean for authorship
https://github.com/NRanjan-17/device_xiaomi_mido_pixel/commit/bf65d99158b7d88ed88ee65a4c813ff54f6e92df

**Comment by rk134** [comment]
> i also mean for authorship [NRanjan-17/device_xiaomi_mido_pixel@bf65d99](https://github.com/NRanjan-17/device_xiaomi_mido_pixel/commit/bf65d99158b7d88ed88ee65a4c813ff54f6e92df)

im not a reviewer for maintainerships, but im also a accepted maintainer

im just going to be brutally honest, you need to fix your commit history, and use proper authorship. 
when you do this, you are showing that you are well-versed in git, and have a good idea on commit maintaining.

https://github.com/NRanjan-17/device_xiaomi_mido_pixel/commit/9edf2e55c0efb81680205a14c2deb5c695cb2d05
this commit does not have authorship, as the original author was zeelog.
you also havent actually imported init.class_main.sh.

https://github.com/NRanjan-17/device_xiaomi_mido_pixel/commit/7a8cb09a9d9d552f9816c56b94b752fc9500d8f3
this commit was picked 4 times, and still has the original notes.

please stop spamming the issues thread until you have proper tree maintaining, and ensure that before you apply, your commit history CLEARLY shows that you have intermediate/higher knowledge in git. 

please also use services such as gitpod/gcs for using git, these free remote servers also have decent internet speeds, which will allow you to properly maintain your trees.

your commit must follow this format:

device: sub-folder (optional): short description of change

Some tools for learning git:
https://www.atlassian.com/git

please re-apply once you show that you have proper tree commit history.
