### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Dobsgw** [PixelExperience/official_devices#2749]
## Device you want to apply for

Apollo

## Device tree sources

https://github.com/Dobsgw/device-xiaomi-apollo-1
https://github.com/Dobsgw/device_xiaomi_sm8250-common-1
https://github.com/Dobsgw/vendor_xiaomi-1
https://github.com/Dobsgw/android_kernel_xiaomi_sm8250
https://gitlab.com/Dobsgw/apollo-firmware
https://github.com/kdrag0n/proton-clang

## Number of ROM's you maintain officially

1 - ArrowOS
Previously EvoX for Sagit and Twolip

## Any Exceptions/special concern?

Let me save this cursed device. It deserves PE. I did see that someone is already working on the PE tree so no worries if I'm not needed!
According to the rules I can't make 1 build and apply, but Arrow has been going for over a year with the same device tree. Just wanted to make you aware we have maintainers available to pick up PE.

### Telegram username

@Dobsgw

### GitHub username

Dobsgw

**Comment by ZIDAN44** [comment]
Hello There !

Since we already have common trees for sm8250 so you need to use them and push commits to your needs or use standalone trees..

**Comment by Dobsgw** [comment]
Hey! 
It doesn't really make sense for me to adapt the existing trees to what will end up being my trees anyway. 
Could we create a new branch?

**Comment by ZIDAN44** [comment]
> Hey! It doesn't really make sense for me to adapt the existing trees to what will end up being my trees anyway. Could we create a new branch?

@Hlcpereira

**Comment by Hlcpereira** [comment]
We have restrictions in such manner as according to the Maintainers' Code of Conduct. What can be done is fully decommonize the device.

**Comment by Hlcpereira** [comment]
Also, you might have to consider two factors into this: 

1 - The maintainers can negotiate with each other about what comes up to the tree and the decisions to what goes where, so communication between the alioth maintainer can be arranged.
2 - You may not end up being the only one in the project with the device, hence a co-maintainship between yourself and someone else will, if this ought to happen, be "in the cards on the table" after all if your application is approved.

It's desirable to have an agreement upon the common-tree usage rather than fully decommonize the device straight away, unless done prior to the application (which we may end up considering that you've analyzed the common-tree prior to the application), mainly considering the fact that apollo may have two members with the device in the end of the day in the project, so opinions may vary a lot in the subject (This is valid for most, if not all devices, whether being in the current device roster or not), but again negotiation is desirable.

Again decommonizing is not restricted per se as lmi, as an example, has done it in the end of the day.

**Comment by Dobsgw** [comment]
Okay totally understood. I don't think I have time to negotiate on the common tree and it looks good as it is so not sure I want to interfere with alioth anyway. Gonna leave it for now. Thanks guys :)
