### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by corradonardone** [PixelExperience/official_devices#3043]
## Device you want to apply for

Xiaomi 12 Lite (Taoyao)

## Device tree sources

https://github.com/erwinabs/android_device_xiaomi_taoyao-twrp
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/taoyao-s-oss
https://github.com/MiCode/vendor_qcom_opensource_wlan/tree/taoyao-s-oss

## Number of ROM's you maintain officially

1

## Any Exceptions/special concern?

No

### Telegram username

@Z3ldaSlayer

### GitHub username

clarianx

**Comment by Hlcpereira** [comment]
Hello thanks for applying however the application must be rejected.

"Why?"
1 - The most important one is that this application seems to be more like a request to have PE available for this device rather than an actual application, and if it's indeed an application, that's clearly a troll one (lol).
2 - The sources linked are evidently not the proper ones to build PE.
3 - It's clear upon just inspecting your Github profile that you have no experience of how to work with a custom ROM. The knowledge level is given pretty clear as per point #2 

Best regards.
