### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by log1cs** [PixelExperience/official_devices#3150]
### Device you want to apply for

Nokia 8 2017, Repartitioned (NLA)

### Device Tree Sources

Device tree: https://github.com/log1cs/android_device_nokia_NLA at branch pe-thirteen
Kernel source: https://github.com/log1cs/kernel_nokia_msm8998 at branch rebase/lineage-20
Vendor tree: https://github.com/log1cs/android_vendor_nokia_NLA at branch lineage-20

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

The reason why the device codename changed to NLA (not NB1) is because we don't want users to flash treble ROMs on top of non-repartitioned devices.
To prevent users flashing treble ROMs on top of non-treble partition table, we changed the codename of the device to prevent it.

### Telegram username

@log1cs

### GitHub username

log1cs

**Comment by log1cs** [comment]
Temporary closing.

Reason: Noticed a bug that can completely ruin user experience, addressing the issue.
Will repoen the ticket when it's ready.

**Comment by log1cs** [comment]
Reopening the application. 
One question: Can I use Lineage kernel? I just rebased my kernel on that one.

**Comment by RisenID** [comment]
Hello,
Hope you are doing well and thanks for your interest in taking a part of the project. Unfortunately, due to android 14 release next month, we are not taking in any new maintainers for android 13 as of now. We look forward to seeing your progress and recieving your application for android 14 in the coming few months.
