### ISSUE TITLE
Resurrection of Xiaomi Mi 11i / Xiaomi Mi11X Pro / Redmi K40 Pro / Pro+ (haydn) New maintainer

### ISSUE THREAD

**Issue by sadoyui** [PixelExperience/official_devices#3171]
### Device you want to apply for

Xiaomi Mi 11i / Xiaomi Mi11X Pro / Redmi K40 Pro / Pro+ (haydn)

### Device Tree Sources

https://github.com/haydn-development/device_xiaomi_haydn
https://github.com/haydn-development/kernel_xiaomi_haydn
https://github.com/haydn-development/vendor_xiaomi_haydn
https://gitlab.com/William_sado/vendor_xiaomi_haydn-firmware

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

All hardware working Good

### Telegram username

@William_sadoyui

### GitHub username

https://github.com/sadoyui

**Comment by RisenID** [comment]
Hello,
Hope you are doing well and thanks for your interest in taking a part of the project. Unfortunately, due to android 14 release next month, we are not taking in any new maintainers for android 13 as of now. We look forward to seeing your progress and recieving your application for android 14 in the coming few months.
