### ISSUE TITLE
New maintainer for Redmi Note 7/7s

### ISSUE THREAD

**Issue by c0pt4n** [PixelExperience/official_devices#3184]
### Device you want to apply for

Redmi Note 7/7s (lavender)

### Device Tree Sources

https://github.com/Coptan99/device_xiaomi_lavender

https://github.com/Coptan99/vendor_xiaomi_lavender

https://github.com/Coptan99/kernel_xiaomi_lavender

### Number of ROM's you maintain officially

2 (Evo, Elixir)

### Any Exceptions/special concern?

I maintained PE unofficially for 2 months earlier then stopped when it became official for lavender and today I built a new build again :)

### Telegram username

AlCoptan99

### GitHub username

Coptan99

**Comment by RisenID** [comment]
Hello,
Hope you are doing well and thanks for your interest in taking a part of the project. Unfortunately, due to android 14 release next month, we are not taking in any new maintainers for android 13 as of now. We look forward to seeing your progress and recieving your application for android 14 in the coming few months.

**Comment by c0pt4n** [comment]
> Hello, Hope you are doing well and thanks for your interest in taking a part of the project. Unfortunately, due to android 14 release next month, we are not taking in any new maintainers for android 13 as of now. We look forward to seeing your progress and recieving your application for android 14 in the coming few months.

Okay, I hope to get in soon :)
