### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by StereoBlade12** [PixelExperience/official_devices#3188]
### Device you want to apply for

Redmi Note 12 4G (tapas)

### Device Tree Sources

Device Tree: 
https://github.com/Agatha-Prjkt/device_xiaomi_topaz

Device Vendor:
https://gitlab.com/agathasenpai/vendor_xiaomi_topaz

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

No

### Telegram username

StereoBlade12

### GitHub username

StereoBlade12

**Comment by RisenID** [comment]
Hello,
Hope you are doing well and thanks for your interest in taking a part of the project. Unfortunately, due to android 14 release next month, we are not taking in any new maintainers for android 13 as of now. We look forward to seeing your progress and recieving your application for android 14 in the coming few months.
