### ISSUE TITLE
New maintainer for Google Pixel 3 & Google Pixel 3 XL

### ISSUE THREAD

**Issue by jrjmt** [PixelExperience/official_devices#3192]
### Device you want to apply for

Google Pixel 3 (blueline) & Google Pixel 3 XL (crosshatch)

### Device Tree Sources

https://github.com/PixelExperience-Devices/device_google_crosshatch
https://github.com/PixelExperience-Devices/kernel_google_bluecross
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_google_blueline
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_google_crosshatch

### Number of ROM's you maintain officially

1

### Any Exceptions/special concern?

NIL

### Telegram username

@jrjmt

### GitHub username

@jrjmt

**Comment by RisenID** [comment]
Hello,
Hope you are doing well and thanks for your interest in taking a part of the project. Unfortunately, due to android 14 release next month, we are not taking in any new maintainers for android 13 as of now. We look forward to seeing your progress and recieving your application for android 14 in the coming few months.
