### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by CEKIKOFGAMERS** [PixelExperience/official_devices#3204]
### Device you want to apply for

Poco X5 5G (moonstone)

### Device Tree Sources

https://github.com/stone-devs/device_xiaomi_stone

### Number of ROM's you maintain officially

0

### Any Exceptions/special concern?

No

### Telegram username

@CEKIKOFGAMERS

### GitHub username

CEKIKOFGAMERS

**Comment by RisenID** [comment]
Hello,
Hope you are doing well and thanks for your interest in taking a part of the project. Unfortunately, due to android 14 release next month, we are not taking in any new maintainers for android 13 as of now. We look forward to seeing your progress and recieving your application for android 14 in the coming few months.
